### PR TITLE
Updated docs

### PR DESCRIPTION
**Pull request by sondrelg**

### CODE REVIEW

**Comment by sondrelg** [comment]
@Goldziher, seeing that you're using the package in another capacity than I am, would you be interested in reading over the revised docs for #74? They include changes from #66.

If you are, you just need to `cd` into docs and run `make html` to build docs, then you can, e.g., open them in your browser by accessing the build folder file path.

**Comment by Goldziher** [comment]
Sure, im checking it out. 

btw the .bat file doesn't work for me, i simply ran "sphinx-build ./ ./html *.rst" in the docs folder to build

**Comment by Goldziher** [comment]
looks good :)

**Review by sondrelg — COMMENTED** [review]
OK

**Pull request merged**
